export const celebrities = [
  'Neymar',
  'Pelé',
  'Silvio Santos',
  'Xuxa',
  'Anitta',
  'Luciano Huck',
  'Ivete Sangalo',
  'Roberto Carlos',
  'Gisele Bündchen',
  'Ronaldinho Gaúcho',
  'Faustão',
  'Galvão Bueno',
  'Lula',
  'Bolsonaro',
  'Chico Buarque',
  'Caetano Veloso',
  'Fernanda Montenegro',
  'Wagner Moura',
  'Rodrigo Santoro',
  'Bruna Marquezine',
  'Whindersson Nunes',
  'Felipe Neto',
  'Ratinho',
  'Ana Maria Braga',
  'William Bonner',
  'Drauzio Varella',
  'Zeca Pagodinho',
  'Seu Jorge',
  'Claudia Leitte',
  'Luan Santana',
  'Gusttavo Lima',
  'Juliette',
  'Eliana',
  'Sabrina Sato',
  'Marcos Mion',
]
