export const movies = [
  'Titanic',
  'O Poderoso Chefão',
  'Matrix',
  'Star Wars',
  'Harry Potter',
  'Senhor dos Anéis',
  'Vingadores',
  'Homem-Aranha',
  'Batman',
  'Jurassic Park',
  'Forrest Gump',
  'O Rei Leão',
  'Toy Story',
  'Procurando Nemo',
  'Shrek',
  'Frozen',
  'Pantera Negra',
  'Coringa',
  'Interestelar',
  'A Origem',
  'O Sexto Sentido',
  'Gladiador',
  'Tropa de Elite',
  'Cidade de Deus',
  'Central do Brasil',
  'Bacurau',
  'O Auto da Compadecida',
  'Minha Mãe é Uma Peça',
  'De Volta para o Futuro',
  'E.T.',
  'Tubarão',
  'Os Incríveis',
  'Divertida Mente',
  'Coco',
  'Avatar',
]
